---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含多項新功能與增強功能。Cloud Volumes ONTAP 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含多項新功能與增強功能。Cloud Volumes ONTAP

最新版的BlueXP也會提供其他功能和增強功能。請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 9.9.1 P8（2022年5月15日）

如果Cloud Volumes ONTAP 您有執行3.9.13版或更新版本的Connector、Microsoft Azure現在可提供9.9.1 P8修補程式以供使用。BlueXP會提示您將現有系統升級至此修補程式版本。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P8["檢視P8修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.9.1 P7（2022年2月21日）

如果Cloud Volumes ONTAP 您有執行3.9.15版或更新版本的Connector、Microsoft Azure現在可提供9.9.1 P7修補程式以供使用。BlueXP會提示您將現有系統升級至此修補程式版本。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P7["檢視P7修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.9.1修補程式（2022年2月3日）

有兩個Cloud Volumes ONTAP 新的修補程式可供使用：

* AWS和Google Cloud中的9.9.1 p6
* Microsoft Azure中的9.9.1 P3


BlueXP會提示您將現有系統升級至這些修補程式版本。

* https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P6["檢視在p6修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）
* https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P3["檢視P3修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）




== 9.9.1 GA（2021年7月21日）

目前已推出《The General Availability》（GA）版Cloud Volumes ONTAP 的《The》（英文）。GA版本包含錯誤修正。

BlueXP會提示您升級執行下列任一版本的現有系統：9.9.1 Release Candidate、9.1.0或9.8。



== 9.9.1更新（2021年7月7日）

BlueXP 3.9.8版本推出下列變更。

* 全新的充電方法Cloud Volumes ONTAP 可供使用。
+
** *容量型BYOL*：容量型授權可讓您依照Cloud Volumes ONTAP 容量的每一TiB付費。授權與您的NetApp帳戶有關、只Cloud Volumes ONTAP 要您的授權有足夠的容量、就能建立多個支援系統。容量型授權以套件形式提供、包括_Essentials或_Professional_。
** * Freemium產品*：Freemium可讓您免費使用Cloud Volumes ONTAP NetApp提供的所有功能（雲端供應商仍需付費）。每個系統的分配容量上限為500 GiB、而且沒有支援合約。您最多可擁有10個Freemium系統。
+
link:concept-licensing.html["深入瞭解這些授權選項"]。



* 在AWS中Cloud Volumes ONTAP 、利用下列充電方法支援m5dn.24xLarge執行個體類型：PAYGO Premium、容量型授權（BYOL）和節點型授權（BYOL）。
* 在Google Cloud中Cloud Volumes ONTAP 、支援平衡式持續磁碟（PD平衡）。這些SSD可提供較低的每GiB IOPS、藉此平衡效能與成本。
* Google Cloud的全新Cloud Volumes ONTAP 推出的功能不再支援Custom-4-16384機器類型。
+
如果您在此機器類型上執行現有的系統、您可以繼續使用、但我們建議您切換至n2-Standard-4機器類型。



https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["深入瞭解BlueXP的新功能"^]。



== 9.9.1更新（2021年6月3日）

最新的BlueXP 3.9.7版本推出新的專業套件支援、讓您Cloud Volumes ONTAP 使用AWS Marketplace的年度合約來搭售各種版本的產品Cloud Backup Service 。

link:reference-configs-aws.html["深入瞭解此授權選項。"]



== 9.9.1候選版本（2021年5月24日）

《候選版本》現已在AWS、Azure和Google Cloud Platform中推出。Cloud Volumes ONTAP

除了所介紹的功能之外 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["部分9.9.1 ONTAP"^]、Cloud Volumes ONTAP 本版的《》包含下列內容：

* <<支援Azure中的S3 ONTAP>>
* <<以高速寫入速度提升AWS效能>>
* <<AWS中的IO2開機磁碟>>




=== 支援Azure中的S3 ONTAP

您現在可以在Cloud Volumes ONTAP Azure中提供S3物件儲存。除了傳統的檔案型傳輸協定（例如NFS和SMB）之外、適用於Microsoft Azure的支援S3作為橫向擴充儲存設備的選項。Cloud Volumes ONTAP

請注意下列事項：

* 搭配使用功能的S3的主要用途是ONTAP 一般用途物件儲存區。Cloud Volumes ONTAP
* 目前、Cloud Volumes ONTAP AWS或Google Cloud不支援使用支援S3傳輸協定。
* BlueXP無法提供ONTAP 任何有關「支援不支援」S3功能的管理功能。


使用CLI是設定S3用戶端從Cloud Volumes ONTAP 功能支援的最佳實務做法。如需詳細資訊、請參閱 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3組態電源指南"^]。



=== 以高速寫入速度提升AWS效能

我們已提升Cloud Volumes ONTAP 了VMware的處理量效能 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["高速寫入"^] 在支援的執行個體類型上啟用。



=== AWS中的IO2開機磁碟

在AWS中、新Cloud Volumes ONTAP 的更新版的開機磁碟現在是已配置的IOPS SSD（IO2）磁碟區。IO2磁碟區的可靠性比IO1磁碟區高、而IO1磁碟區先前是用於開機磁碟。



== 所需版本的BlueXP Connector

BlueXP Connector必須執行3.9.6版或更新版本、才能部署新Cloud Volumes ONTAP 的版本的更新版本、並將現有系統升級至9.9.1版。



== 升級附註

* 必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。
* 您可以從Cloud Volumes ONTAP 9.9.0版本和9.8版本升級至版本的版本。BlueXP會提示您將現有Cloud Volumes ONTAP 的版本更新至9.9.1。
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。
* 在 AWS 中、新的 Cloud Volumes ONTAP 部署不再支援 C4 、 M4 和 R4 EC2 執行個體類型。如果現有的系統執行於c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。如果您無法變更執行個體類型、則必須在升級之前啟用增強的網路功能。
+
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["瞭解如何使用 C4 、 M4 和 R4 EC2 執行個體類型升級 AWS"^]。
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

+
請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。





=== DS3_v2

從9.9.1版開始、DS3_v2 VM類型不再支援新的和現有Cloud Volumes ONTAP 的版本。如果此VM類型上有執行的現有系統、則在升級至9.9.1之前、您必須先變更VM類型。
